apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  ports:
  - port: ${PYTHON_PORT:-8000}
    targetPort: ${PYTHON_PORT:-8000}
    name: http
  selector:
    app: python 