apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  ports:
  - port: ${BACKEND_PORT:-3001}
    targetPort: ${BACKEND_PORT:-3001}
    name: http
  selector:
    app: backend 