apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ${PROJECT_NAME:-fullstack}
data:
  NODE_ENV: ${NODE_ENV:-production}
  VITE_API_URL: "http://backend:${BACKEND_PORT:-3001}/api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${PROJECT_NAME:-fullstack}/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NODE_ENV
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1 