apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ${PROJECT_NAME:-fullstack}
data:
  MYSQL_DATABASE: ${DB_DATABASE:-fullstack_db}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ${PROJECT_NAME:-fullstack}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_BASE64:-cGFzc3dvcmQ=}  # Default: "password" in base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-u", "root", "-p${DB_PASSWORD:-password}"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-u", "root", "-p${DB_PASSWORD:-password}"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ${PROJECT_NAME:-fullstack}
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql
  clusterIP: None  # Headless service for StatefulSet 